/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBookingRouteImport } from './routes/_authenticated/booking'
import { Route as AuthenticatedKasirRouteImport } from './routes/_authenticated/kasir'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedPelangganRouteImport } from './routes/_authenticated/pelanggan'
import { Route as AuthenticatedPembayaranRouteImport } from './routes/_authenticated/pembayaran'
import { Route as AuthenticatedPromoRouteImport } from './routes/_authenticated/promo'
import { Route as AuthenticatedTarifRouteImport } from './routes/_authenticated/tarif'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingRoute = AuthenticatedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasirRoute = AuthenticatedKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPelangganRoute = AuthenticatedPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPembayaranRoute = AuthenticatedPembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromoRoute = AuthenticatedPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarifRoute = AuthenticatedTarifRouteImport.update({
  id: '/tarif',
  path: '/tarif',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/kasir': typeof AuthenticatedKasirRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pembayaran': typeof AuthenticatedPembayaranRoute
  '/promo': typeof AuthenticatedPromoRoute
  '/tarif': typeof AuthenticatedTarifRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/kasir': typeof AuthenticatedKasirRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pembayaran': typeof AuthenticatedPembayaranRoute
  '/promo': typeof AuthenticatedPromoRoute
  '/tarif': typeof AuthenticatedTarifRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/booking': typeof AuthenticatedBookingRoute
  '/_authenticated/kasir': typeof AuthenticatedKasirRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/pelanggan': typeof AuthenticatedPelangganRoute
  '/_authenticated/pembayaran': typeof AuthenticatedPembayaranRoute
  '/_authenticated/promo': typeof AuthenticatedPromoRoute
  '/_authenticated/tarif': typeof AuthenticatedTarifRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/booking'
    | '/kasir'
    | '/laporan'
    | '/pelanggan'
    | '/pembayaran'
    | '/promo'
    | '/tarif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/booking'
    | '/kasir'
    | '/laporan'
    | '/pelanggan'
    | '/pembayaran'
    | '/promo'
    | '/tarif'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/booking'
    | '/_authenticated/kasir'
    | '/_authenticated/laporan'
    | '/_authenticated/pelanggan'
    | '/_authenticated/pembayaran'
    | '/_authenticated/promo'
    | '/_authenticated/tarif'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking': {
      id: '/_authenticated/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kasir': {
      id: '/_authenticated/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof AuthenticatedKasirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pelanggan': {
      id: '/_authenticated/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof AuthenticatedPelangganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembayaran': {
      id: '/_authenticated/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof AuthenticatedPembayaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promo': {
      id: '/_authenticated/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof AuthenticatedPromoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarif': {
      id: '/_authenticated/tarif'
      path: '/tarif'
      fullPath: '/tarif'
      preLoaderRoute: typeof AuthenticatedTarifRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingRoute: typeof AuthenticatedBookingRoute
  AuthenticatedKasirRoute: typeof AuthenticatedKasirRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedPelangganRoute: typeof AuthenticatedPelangganRoute
  AuthenticatedPembayaranRoute: typeof AuthenticatedPembayaranRoute
  AuthenticatedPromoRoute: typeof AuthenticatedPromoRoute
  AuthenticatedTarifRoute: typeof AuthenticatedTarifRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingRoute: AuthenticatedBookingRoute,
  AuthenticatedKasirRoute: AuthenticatedKasirRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedPelangganRoute: AuthenticatedPelangganRoute,
  AuthenticatedPembayaranRoute: AuthenticatedPembayaranRoute,
  AuthenticatedPromoRoute: AuthenticatedPromoRoute,
  AuthenticatedTarifRoute: AuthenticatedTarifRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
